#! /bin/sh
set -e

case "$1" in
    remove|upgrade|deconfigure)
		update-alternatives --remove libswt-3.5-java \
                /usr/share/java-config/libswt-gtk-3.5-java
		update-alternatives --remove swt.jar \
                /usr/lib/java/swt-gtk-3.5.1.jar
	;;
    failed-upgrade)
	;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
