#! /bin/sh
set -e

case "$1" in
    configure)
        update-alternatives --install \
                /usr/share/java/swt.jar \
                swt.jar \
                /usr/share/java/swt-gtk-3.8.jar \
                103
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
